# Generated by Django 6.0 on 2025-12-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_request_meds_request_meds_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="assigned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Lab"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="assignment_status",
            field=models.CharField(
                choices=[
                    ("Unassigned", "Unassigned"),
                    ("Assigned", "Assigned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Unassigned",
                max_length=20,
            ),
        ),
    ]
