# Generated by Django 6.0 on 2025-12-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_request_assigned_date_request_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="microbiology_pdf",
            field=models.FileField(
                blank=True,
                help_text="Upload the microbiology report PDF",
                null=True,
                upload_to="reports/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="pdf_uploaded_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
